const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
fs.mkdirSync('test-artifacts',{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:8765');
 // Isolated, supported legacy save: a mastered refuge, no new districts unlocked.
 const fixture=Array(28).fill(0);
 Object.assign(fixture,{0:2,1:50000,2:1,4:1,8:4,9:0,10:3,11:3,12:500,13:20,14:100,15:4,16:4,17:0,24:3,25:3,26:3,27:3});
 await page.evaluate(v=>{localStorage.clear();localStorage.setItem('withsurvival-save-v2',JSON.stringify(v));},fixture);
 await page.reload();await page.click('#play');
 await page.waitForFunction(()=>window.__withsurvival?.state?.districts?.length===8,null,{timeout:15000});
 let s=await page.evaluate(()=>window.__withsurvival.state);
 assert.equal(s.districtUpgrades.length,72,'eight districts export nine authoritative upgrade records each');
 assert.equal(s.districts.filter(d=>d.unlocked).length,0,'legacy save starts without new districts');
 await page.click('#nav-expeditions');await page.click('#btn-expand');await page.waitForTimeout(350);
 const before=await page.evaluate(()=>({time:window.__withsurvival.state.time,worldTime:window.__withsurvival.state.worldTime}));
 await page.waitForTimeout(500);
 assert.deepEqual(await page.evaluate(()=>({time:window.__withsurvival.state.time,worldTime:window.__withsurvival.state.worldTime})),before,'EXPANSION pauses both simulation clocks');
 assert.equal(await page.locator('.district-card').count(),8);
 await page.evaluate(()=>{window.testDistrictFocusButton=document.querySelector('#district-next button:not(.primary)');});
 await page.waitForTimeout(600);
 assert.equal(await page.evaluate(()=>window.testDistrictFocusButton.isConnected&&window.testDistrictFocusButton===document.querySelector('#district-next button:not(.primary)')),true,'next-route buttons retain DOM identity across HUD refreshes');
 assert.equal(await page.locator('#district-next button.primary').isDisabled(),false,'mastered refuge can open fishing district');
 await page.locator('#district-next button').filter({hasText:'Voir la dalle'}).click();
 assert.equal(await page.locator('#district-panel').evaluate(n=>n.open),false);
 let guide=await page.evaluate(()=>window.__withsurvival.guide());
 assert.equal(guide.x,s.districts[0].tileX);assert.equal(guide.z,s.districts[0].tileZ);
 await page.click('#nav-expeditions');await page.click('#btn-expand');await page.locator('#district-next button.primary').click();
 await page.waitForFunction(()=>window.__withsurvival.state.districts[0].unlocked);
 s=await page.evaluate(()=>window.__withsurvival.state);
 assert.equal(s.districts.filter(d=>d.unlocked).length,1,'unlock purchases only next district');
 assert.equal(s.districts[1].unlocked,false,'next farm requires actual fishing mastery');
 assert.ok((await page.locator('.district-card').first().innerText()).includes('Poissons'));
 assert.ok((await page.locator('.district-card').first().innerText()).includes('Filets'));
 assert.equal(await page.locator('#district-next button.primary').isDisabled(),true,'farm remains gated by real preceding production');
 await page.screenshot({path:'test-artifacts/mobile-district-expansion.png'});
 await page.locator('.district-card').first().locator('.district-controls').first().locator('button').last().click();
 guide=await page.evaluate(()=>window.__withsurvival.guide());
 assert.equal(guide.x,s.districts[0].marketX);assert.equal(guide.z,s.districts[0].marketZ-2.5,'market guide targets actual reception zone');
 await page.click('#nav-expeditions');await page.click('#btn-expand');
 const initialSourceLevel=s.districts[0].sourceLevel;
 const source=page.locator('.district-card').first().locator('.district-machine').filter({hasText:'Récolte ·'}).locator('button');
 await source.click();await page.waitForTimeout(350);
 s=await page.evaluate(()=>window.__withsurvival.state);const level=s.districts[0].sourceLevel;
 assert.equal(level,initialSourceLevel+1,'source purchase changes authoritative level');
 await page.reload();await page.waitForFunction(()=>window.__withsurvival?.state?.districts?.[0]?.unlocked);
 s=await page.evaluate(()=>window.__withsurvival.state);assert.equal(s.districts[0].sourceLevel,level,'district upgrades survive save/reload');
 assert.equal(s.districts[1].unlocked,false);assert.equal(s.districtUpgrades.length,72);
 assert.deepEqual(errors,[],'no browser runtime errors');
 console.log('PASS: mobile EXPANSION, 8 real districts/72 upgrades, dual-clock pause, gated fishing unlock, actual reception guides, upgrade and saved progression.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
